before_install:
  - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - npm install -g grunt-cli

install:
  - bundle install
  - npm install grunt grunt-html --save-dev

script:
  - bundle exec jekyll build
  - grunt test
  - bundle exec htmlproof ./_site

# environment
language: ruby
rvm:
  - "2.1"

notifications:
  email:
    recipients:
      - "azaroth42@gmail.com"
      - "blalbrit@stanford.edu"
      - "jpstroop@gmail.com"
      - "michael.appleby@yale.edu"
      - "simeon.warner@gmail.com"
      - "snydman@stanford.edu"
    on_success: "change"
    on_failure: "change"
