# environment
language: ruby
cache: bundler
rvm:
  - 2.7.1
cache:
  bundler: true
  directories:
  - $TRAVIS_BUILD_DIR/tmp/.htmlproofer
  - $HOME/.local

before_install:
  - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true

install:
  - bundle install

notifications:
  email:
    recipients:
      - "staff@iiif.io"
    on_success: "change"
    on_failure: "change"
