before_install:
  - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true

script:
  - bundle exec jekyll build --trace
  - bundle exec htmlproof ./_site

# environment
language: ruby
rvm:
  - 2.1

notifications:
  email: false
