before_install:
  - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true

script:
  - bundle exec jekyll build --trace
  - bundle exec htmlproof ./_site

# environment
language: ruby
rvm:
  - 2.1

notifications:
  email:
    recipients:
      - "azaroth42@gmail.com"
      - "blalbrit@stanford.edu"
      - "jpstroop@gmail.com"
      - "michael.appleby@yale.edu"
      - "simeon.warner@gmail.com"
      - "snydman@stanford.edu"
    on_success: "change"
    on_failure: "always"
    template:
      - "%{repository}//%{branch}@%{commit} by %{author}: %{message} - %{build_url}"

