name: IIIF | International Image Interoperability Framework
markdown: kramdown
pygments: true
exclude: [ dev.sh, publish.sh]
kramdown:
  input: GFM
  parse_block_html: true
  toc_levels: 2..6

image_api:
  latest:
    major: 1
    minor: 1
    patch: 0
presentation_api:
  latest:
    major: 1
    minor: 0
    patch: 0

